# Generated by Django 4.1.7 on 2023-03-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_emblem',
            field=models.ImageField(upload_to='city_emblem/', verbose_name='Герб'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='image',
            field=models.ImageField(upload_to='sight/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
