# Generated by Django 4.1.7 on 2023-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0002_alter_city_city_emblem_alter_sight_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default=None, upload_to='<django.db.models.fields.CharField>/photo/', verbose_name='Фото города'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='city_emblem',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>/city_emblem/', verbose_name='Герб'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='image',
            field=models.ImageField(upload_to='None/sight/', verbose_name='Изображение'),
        ),
    ]
