# Generated by Django 4.1.7 on 2023-03-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0003_city_image_alter_city_city_emblem_alter_sight_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='title',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='city',
            name='city_emblem',
            field=models.ImageField(upload_to='city_emblem/', verbose_name='Герб'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(upload_to='city_photo/', verbose_name='Фото города'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='image',
            field=models.ImageField(upload_to='sight/', verbose_name='Изображение'),
        ),
    ]
