# Generated by Django 4.1.7 on 2023-03-21 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0004_rename_title_city_description_alter_city_city_emblem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sight',
            old_name='title',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='sight',
            name='image',
        ),
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.TextField(verbose_name='Краткое описание города'),
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Название')),
                ('kitchen', models.CharField(max_length=300, verbose_name='Кухня')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='restaurants/', verbose_name='Основное фото')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_in_Russia.city')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
            },
        ),
        migrations.CreateModel(
            name='PhotoAttractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('photo', models.ImageField(upload_to='photo_attractions/', verbose_name='Фото достопримечательности')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_in_Russia.sight')),
            ],
            options={
                'verbose_name': 'Фото достопримечательности',
                'verbose_name_plural': 'Фото достопримечательностей',
            },
        ),
        migrations.CreateModel(
            name='InteriorPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='interior_photo/', verbose_name='Фото интерьера')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_in_Russia.restaurants')),
            ],
            options={
                'verbose_name': 'Фото интерьера',
                'verbose_name_plural': 'Фото интерьера',
            },
        ),
    ]
