# Generated by Django 4.1.7 on 2023-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0005_rename_title_sight_description_remove_sight_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='link',
            field=models.URLField(default='Нет сайта', verbose_name='Ссылка'),
        ),
        migrations.AddField(
            model_name='restaurants',
            name='place',
            field=models.CharField(default='Нет адреса', max_length=150, verbose_name='Адрес'),
            preserve_default=False,
        ),
    ]
