# Generated by Django 4.1.7 on 2023-03-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0006_restaurants_link_restaurants_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='founding_date',
            field=models.CharField(max_length=30, verbose_name='Дата основания города'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='description',
            field=models.TextField(max_length=1500, verbose_name='Описание'),
        ),
    ]
