# Generated by Django 4.1.7 on 2023-03-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0007_alter_city_founding_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Reviews',
        ),
    ]
