# Generated by Django 4.1.7 on 2023-03-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0009_rename_city_reviews_city2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='city2',
            new_name='city',
        ),
    ]
