# Generated by Django 4.1.7 on 2023-03-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0010_rename_city2_reviews_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travel_in_Russia.ratingstar', verbose_name='звезда'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_in_Russia.city', verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_in_Russia.reviews', verbose_name='родитель'),
        ),
    ]
