# Generated by Django 4.1.7 on 2023-03-29 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0013_alter_rating_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_in_Russia.ratingstar', verbose_name='звезда'),
        ),
    ]
