# Generated by Django 4.1.7 on 2023-04-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_in_Russia', '0018_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='../static/images/te2.jpg', upload_to='profile/', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='description',
            field=models.TextField(max_length=1550, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='place',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
    ]
